# Generated by Django 4.2.5 on 2023-11-02 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post_like_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followee_id",
            new_name="followee",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="follower_id",
            new_name="follower",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="liker_id",
            new_name="liker",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="poster_id",
            new_name="poster",
        ),
    ]
