# Generated by Django 4.2.5 on 2023-11-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_rename_followee_id_follow_followee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.post",
            ),
            preserve_default=False,
        ),
    ]
